direction: down

style: {
  fill: transparent
}

# --- FILA 1: ANÁLISIS Y SEGURIDAD ---
fila_1: {
  label: ""
  direction: right
  style: {
    fill: "#0f172a"
    stroke: "#38bdf8"
    stroke-width: 2
    border-radius: 8
    font-color: "#bae6fd"
  }

  origen: "Código Fuente\n[.rs]" {
    style: { fill: "#1e1e38"; stroke: "#818cf8"; font-color: "#c7d2fe"; bold: true }
  }

  frontend: "Frontend (rustc)" {
    direction: right
    style: { fill: "#1e293b"; stroke: "#38bdf8"; font-color: "#ffffff" }

    lexer: "Lexer + Parser\nTokens y sintaxis" {
      style: { fill: "#172554"; stroke: "#60a5fa"; font-color: "#dbeafe" }
    }
    ast: "AST\nÁrbol sintáctico" {
      style: { fill: "#172554"; stroke: "#60a5fa"; font-color: "#dbeafe" }
    }
    macros: "Expansión de macros\nmacro_rules! / derive" {
      style: { fill: "#172554"; stroke: "#60a5fa"; font-color: "#dbeafe" }
    }
    hir: "HIR\nTipos y nombres" {
      style: { fill: "#172554"; stroke: "#60a5fa"; font-color: "#dbeafe" }
    }

    lexer -> ast -> macros -> hir
  }

  middle: "Middle-End" {
    direction: right
    style: { fill: "#451a03"; stroke: "#ea580c"; font-color: "#ffedd5"; bold: true }

    mir: "MIR\nRepresentación intermedia" {
      style: { fill: "#431407"; stroke: "#fb923c"; font-color: "#ffedd5" }
    }
    borrow: "Borrow Checker\nOwnership, borrowing y lifetimes" {
      style: { fill: "#431407"; stroke: "#fb923c"; font-color: "#ffedd5" }
    }

    mir -> borrow
  }

  origen -> frontend -> middle
}

# --- FILA 2: OPTIMIZACIÓN Y MÁQUINA ---
fila_2: {
  label: ""
  direction: right
  style: {
    fill: "#0f172a"
    stroke: "#a855f7"
    stroke-width: 2
    border-radius: 8
    font-color: "#e9d5ff"
  }

  llvm: "Backend (LLVM)" {
    direction: right
    style: { fill: "#1e293b"; stroke: "#c084fc"; font-color: "#ffffff" }

    ir: "LLVM IR\n[.ll / .bc]" {
      style: { fill: "#312e81"; stroke: "#c084fc"; font-color: "#ede9fe" }
    }
    optimize: "Optimizaciones\nopt-level = 0 / 3 / s / z" {
      style: { fill: "#312e81"; stroke: "#c084fc"; font-color: "#ede9fe" }
    }

    ir -> optimize
  }

  asm: "Ensamblador\n[.s / .asm]" {
    style: { fill: "#1e293b"; stroke: "#ec4899"; font-color: "#ffffff" }
  }

  objeto: "Código Objeto\n[.o]" {
    style: { fill: "#1e293b"; stroke: "#ec4899"; font-color: "#ffffff" }
  }

  linker: "Linker (ld / lld)\n+ libstd / Crates" {
    style: { fill: "#064e3b"; stroke: "#34d399"; font-color: "#ecfdf5" }
  }

  binario: "ARTEFACTO FINAL\n[ELF / PE / Mach-O / WASM]" {
    style: { fill: "#065f46"; stroke: "#10b981"; font-color: "#ffffff"; bold: true }
  }

  llvm -> asm -> objeto -> linker -> binario
}

# Conexión entre Fila 1 y Fila 2
fila_1.middle -> fila_2.llvm: "Validaciones superadas"
