use std::sync::{Arc, Mutex};

pub struct LessonsState {
    pub playground_code: String,
    pub playground_output: Arc<Mutex<String>>,
    pub datatypes_code: String,
    pub datatypes_output: Arc<Mutex<String>>,
    pub playground_nube_code: String,
    pub playground_nube_output: Arc<Mutex<String>>,

    pub anim_compilacion_activa: bool,
    pub compilacion_progreso: f32,
    pub compilacion_etapa_seleccionada: usize,

    pub controlflujo_code: String,
    pub controlflujo_output: Arc<Mutex<String>>,
    pub ownership_code: String,
    pub ownership_output: Arc<Mutex<String>>,
    pub strings_ownership_tab: usize,
    pub structs_code: String,
    pub structs_output: Arc<Mutex<String>>,
    pub enums_code: String,
    pub enums_output: Arc<Mutex<String>>,
    pub colecciones_code: String,
    pub colecciones_output: Arc<Mutex<String>>,
    pub vec_sim_len: usize,
    pub vec_sim_cap: usize,
    pub colecciones_tab: usize,
    pub errores_code: String,
    pub errores_output: Arc<Mutex<String>>,
    pub err_pipeline_fail: bool,
    pub traits_code: String,
    pub traits_output: Arc<Mutex<String>>,
    pub genericos_code: String,
    pub genericos_output: Arc<Mutex<String>>,

    pub arr_elem_type: usize,
    pub arr_len: usize,
    pub arr_active_idx: usize,
    pub arr_action_msg: String,
    pub compuestos_tab: usize,
    pub slice_start: usize,
    pub slice_end: usize,
    pub tup_t0: usize,
    pub tup_t1: usize,
    pub tup_t2: usize,
    pub structs_tab: usize,

    pub funciones_code: String,
    pub funciones_output: Arc<Mutex<String>>,
    pub funciones_tab: usize,
    pub iteradores_tab: usize,
    pub enums_tab: usize,
    pub traits_tab: usize,
    pub genericos_tab: usize,
    pub iteradores_code: String,
    pub iteradores_output: Arc<Mutex<String>>,
    pub iter_mode: usize,
    pub iter_filter_even: bool,
    pub arr_code: String,
    pub arr_output: Arc<Mutex<String>>,
    pub slice_code: String,
    pub slice_output: Arc<Mutex<String>>,
    pub tup_code: String,
    pub tup_output: Arc<Mutex<String>>,
    pub compuestos_info_tab: usize,

    pub pilares_step: usize,
    pub anatomy_step: usize,
    pub codelab_reto_actual: usize,
    pub codelab_retos_completados: [bool; 6],
    pub codelab_respuestas: [Option<usize>; 5],
    pub tipo_primitivo_categoria: usize,
    pub tipo_entero_seleccionado: usize,
    pub conceptos_enteros_familia: usize,
    pub estructura_code: String,
    pub estructura_output: Arc<Mutex<String>>,
    pub estructura_tab: usize,
    pub conceptos_tab: usize,
    pub conceptos_codelab_reto_actual: usize,
    pub controlflujo_tab: usize,
    pub controlflujo_is_practica: bool,
    pub conceptos_code: String,
    pub conceptos_output: Arc<Mutex<String>>,
    pub modulos_code: String,
    pub modulos_output: Arc<Mutex<String>>,
    pub modulos_tab: usize,
}

impl Default for LessonsState {
    fn default() -> Self {
        Self {
            playground_code: crate::content::PLAYGROUND_CODE.to_owned(),
            playground_output: Arc::new(Mutex::new(String::new())),
            datatypes_code: crate::content::DATATYPES_CODE.to_owned(),
            datatypes_output: Arc::new(Mutex::new(String::new())),
            playground_nube_code: crate::content::PLAYGROUND_NUBE_CODE.to_owned(),
            playground_nube_output: Arc::new(Mutex::new(String::new())),

            anim_compilacion_activa: false,
            compilacion_progreso: 1.0,
            compilacion_etapa_seleccionada: 4,
            controlflujo_code: crate::content::CONTROL_FLUJO_CODE.to_owned(),
            controlflujo_output: Arc::new(Mutex::new(String::new())),
            ownership_code: crate::content::OWNERSHIP_CODE.to_owned(),
            ownership_output: Arc::new(Mutex::new(String::new())),
            strings_ownership_tab: 0,
            structs_code: crate::content::STRUCTS_CODE.to_owned(),
            structs_output: Arc::new(Mutex::new(String::new())),
            enums_code: crate::content::ENUMS_CODE.to_owned(),
            enums_output: Arc::new(Mutex::new(String::new())),
            colecciones_code: crate::content::COLLECTIONS_CODE.to_owned(),
            colecciones_output: Arc::new(Mutex::new(String::new())),
            vec_sim_len: 3,
            vec_sim_cap: 4,
            colecciones_tab: 0,
            errores_code: crate::content::ERRORS_CODE.to_owned(),
            errores_output: Arc::new(Mutex::new(String::new())),
            err_pipeline_fail: false,
            traits_code: crate::content::TRAITS_CODE.to_owned(),
            traits_output: Arc::new(Mutex::new(String::new())),
            genericos_code: crate::content::GENERICS_CODE.to_owned(),
            genericos_output: Arc::new(Mutex::new(String::new())),
            genericos_tab: 0,
            arr_elem_type: 1,
            arr_len: 5,
            arr_active_idx: 2,
            arr_action_msg: "Inspecciona métodos y accesos a elementos del arreglo".to_string(),
            compuestos_tab: 0,
            slice_start: 1,
            slice_end: 4,
            tup_t0: 1,
            tup_t1: 3,
            tup_t2: 2,
            structs_tab: 0,
            funciones_code: crate::content::FUNCTIONS_CODE.to_owned(),
            funciones_output: Arc::new(Mutex::new(String::new())),
            funciones_tab: 0,
            iteradores_tab: 0,
            enums_tab: 0,
            traits_tab: 0,
            iteradores_code: crate::content::ITERATORS_CODE.to_owned(),
            iteradores_output: Arc::new(Mutex::new(String::new())),
            iter_mode: 0,
            iter_filter_even: true,
            arr_code: crate::content::ARRAYS_CODE.to_owned(),
            arr_output: Arc::new(Mutex::new(String::new())),
            slice_code: crate::content::SLICES_CODE.to_owned(),
            slice_output: Arc::new(Mutex::new(String::new())),
            tup_code: crate::content::TUPLES_CODE.to_owned(),
            tup_output: Arc::new(Mutex::new(String::new())),
            compuestos_info_tab: 0,
            pilares_step: 0,
            anatomy_step: 0,
            codelab_reto_actual: 0,
            codelab_retos_completados: [false, false, false, false, false, false],
            codelab_respuestas: [None; 5],
            tipo_primitivo_categoria: 0,
            tipo_entero_seleccionado: 2,
            conceptos_enteros_familia: 0,
            estructura_code: String::new(),
            estructura_output: Arc::new(Mutex::new(String::new())),
            estructura_tab: 0,
            conceptos_tab: 7,
            conceptos_codelab_reto_actual: 0,
            controlflujo_tab: 0,
            controlflujo_is_practica: false,
            conceptos_code: String::new(),
            conceptos_output: Arc::new(Mutex::new(String::new())),
            modulos_code: crate::content::MODULES_CODE.to_owned(),
            modulos_output: Arc::new(Mutex::new(String::new())),
            modulos_tab: 0,
        }
    }
}
